### ISSUE TITLE
Importing 3 existing projects

### ISSUE THREAD

**Issue by jutunen** [vanillawc/vanillawc#31]
I would like to import 3 of my projects under vanillawc "brand":

https://github.com/jutunen/text-input-datepicker 
https://github.com/jutunen/custom-menu-wrapper
https://github.com/jutunen/custom-arrow

What do you think?

**Comment by evanplaice** [comment]
Yes, absolutely. I have a few questions first.

Do you plan to continue maintaining these packages?

If yes, you'll be added as a member to the org w/ Admin Access + push access to the main branch of the 3 repos.

Are you OK with them being renames with the `wc-` prefix?

It's the only real hard requirement, it makes the web components that come from this org easier to identify and promote.

Are you OK with them being modified to match the existing conventions used in this Org?

I prefer to keep the dev processes, tooling, documentation, CI/CD, etc consistent across all projects.

I'm actually in the process of consolidating the entire toolchain (ie build, minify, lint) into a single project called ESMTK (ES Module Toolkit) to better streamline this and remove as much boilerplate as possible.

---

If all this sounds acceptable, I'll send you an invite to the Org. Once you're a Member you'll be able to transfer the repos over and create new ones if you'd like.

If you'd like to chat you're also welcome to join the Discord https://discord.gg/yGqcGAt. I'm on US MST (Mountain Standard Time).

**Comment by jutunen** [comment]
> Do you plan to continue maintaining these packages?
> 

Yes.

> Are you OK with them being renames with the `wc-` prefix?
> 

Yes.

> Are you OK with them being modified to match the existing conventions used in this Org?
> 
> I prefer to keep the dev processes, tooling, documentation, CI/CD, etc consistent across all projects.
> 

Currently I'm not very eager to add any more dev processes to my projects. Minifying is the only dev process in my projects at the moment, it is totally optional and I provide instructions on how to do it.

Vanillawc demos seem to be in webcomponents.dev. Currently I have my demos running on my own server. Do you have any requirements for the demos?

Regarding documentation, I think that the level/coverage of my documentation surpasses vanillawc "standard" at the moment. I'm not planning to trim any documentation I have done so far.

However, I really would like to find new ways to promote vanilla web components. Maybe a new topic/keyword to github and npmjs, something like _vanilla-js-web-component_ or _vanilla-web-component_?

**Comment by evanplaice** [comment]
Invite sent, you should be able to transfer now. Let me know if you run into issues.

> Currently I'm not very eager to add any more dev processes to my projects. Minifying is the only dev process in my projects at the moment, it is totally optional and I provide instructions on how to do it.

Take a look at [CONTRIBUTING.md](https://github.com/vanillawc/vanillawc/blob/master/CONTRIBUTING.md) for an idea.

A consistent 'start' command and debug configs make live debugging web components easy.

Linting was just updated yesterday to use the new ESM Toolkit

CI/CD configs handle testing and deployment. Publishing to NPM and GitHub Packages is fully automated. To trigger it you can call `npm version major|minor|patch`.

ESMTK is in progress but eventually it'll provide:
- start (live-server)
- lint (StandardJS)
- build (ESBuild)
- minify (ESBuild)
- test is still a WIP (Work In Progress)

> Vanillawc demos seem to be in webcomponents.dev. Currently I have my demos running on my own server. Do you have any requirements for the demos?

No requirements, you can leave them as-is if you prefer.

I like using WCD b/c users can fork/modify the demos to experiment w/ different settings; like CodePen but specifically for Web Components. It also tracks views so I can see which demos are getting visibility. If you'd like to migrate them to WCD, I can get you setup w/ access.

If you want to keep them as-is but save on hosting, I'd recommend hosting them directly from the repo w/ GH pages. Check out `wc-monaco-editor` demo as an example. If you're not familiar w/ GH Pages, I can help.

> Regarding documentation, I think that the level/coverage of my documentation surpasses vanillawc "standard" at the moment. I'm not planning to trim any documentation I have done so far.

I agree, suggestions/feedback for improving the rest of the projects is welcome as well.

> However, I really would like to find new ways to promote vanilla web components. Maybe a new topic/keyword to github and npmjs, something like vanilla-js-web-component or vanilla-web-component?

Any help in this regard is more than welcome. I have a number of remotely successful OSS projects in spite of, not because of, my ability to promote the work. I like `vanilla-web-component`.

The`web-components` keyword is included b/c it's the most common keyword used to look up web component projects on GitHub. The rest of the keywords can be updated and/or removed if they aren't useful. I'm open to suggestions.

---

Quick question, can components be published to WebComponents.org without a bower config now? If so I'd like to remove that anachronism from the rest of the projects.
